default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.secrets.database[:username] %>
  password: <%= Rails.application.secrets.database[:password] %>

development:
  <<: *default
  database: action-cable-example-dev

test:
  <<: *default
  database: action-cable-example-test

production:
  <<: *default
  database: action-cable-example-prod
